name: Benchmark Baseline

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Git Tag Name'
        required: false
      branch_name:
        description: 'Git Branch Name'
        required: true
        default: '1.x'
  push:
    branches: [ 1.x ]
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  benchmark:
    name: "Benchmark Baseline"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.1"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Set Git Ref"
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "GIT_REF=${{ github.ref }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.tag_name }}" != "" ]]; then
            echo "GIT_REF=refs/tags/${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          else
            echo "GIT_REF=${{ github.event.inputs.branch_name }}" >> $GITHUB_ENV
          fi

      - name: "Set Benchmark Tag"
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "PHPBENCH_TAG=1.x" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.tag_name }}" != "" ]]; then
            echo "PHPBENCH_TAG=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          else
            echo "PHPBENCH_TAG=${{ github.event.inputs.branch_name }}" >> $GITHUB_ENV
          fi

      - name: "Checkout to specific ref"
        uses: "actions/checkout@v4"
        with:
          ref: ${{ env.GIT_REF }}

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: none
          tools: composer:v2
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1

      - name: "Get Composer Cache Directory"
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Cache Composer dependencies"
        uses: "actions/cache@v3"
        with:
          path: "${{ steps.composer-cache.outputs.dir }}"
          key: "php-${{ matrix.php-version }}-locked-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: |
            php-${{ matrix.php-version }}-locked-composer-

      - name: "Install locked dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Benchmark"
        run: |
          echo '# Flow PHP - Benchmark - ${{ env.PHPBENCH_TAG }}' >> $GITHUB_STEP_SUMMARY
          echo ' ' >> $GITHUB_STEP_SUMMARY
          echo '---' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          composer test:benchmark -- --tag=${{ env.PHPBENCH_TAG }} --progress=none >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: "Store Benchmark baseline"
        uses: actions/upload-artifact@v3
        with:
          name: phpbench-baseline
          path: ./var/phpbench/
