name: Build Release

on:
  release:
    types:
      - published

jobs:
  build-release:
    name: "Build Release"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        php-version:
          - "8.1"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: none
          tools: composer:v2
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1

      - name: "Get Composer Cache Directory"
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Cache Composer dependencies"
        uses: "actions/cache@v3"
        with:
          path: "${{ steps.composer-cache.outputs.dir }}"
          key: "php-${{ matrix.php-version }}-locked-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: |
            php-${{ matrix.php-version }}-locked-composer-

      - name: "Install locked dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Build PHAR file"
        run: "composer build:phar"

      - name: "Validate Flow PHAR"
        run: |
          ./build/flow.phar --version

      - name: "Import GPG Key"
        uses: crazy-max/ghaction-import-gpg@72b6676b71ab476b77e676928516f6982eef7a41
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: "Sign PHAR"
        run: >
          gpg
          --batch
          --yes
          --local-user="${{ secrets.GPG_USER_EMAIL }}"
          --passphrase="${{ secrets.GPG_PASSPHRASE }}"
          --pinentry-mode="loopback"
          --detach-sign
          --output="./build/flow.phar.asc"
          ./build/flow.phar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/flow-php/flow:${{ github.ref_name }}
          target: flow
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "Upload binaries to release"
        uses: softprops/action-gh-release@v1
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          files: |
            build/flow.phar
            build/flow.phar.asc

      - name: "Get release tag"
        run: |
          RELEASE_TAG=${GITHUB_REF/refs\/tags\//}
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

      - name: "Update Homebrew formula"
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: flow-php
          formula-path: src/tools/homebrew/Formula/flow-php.rb
          homebrew-tap: flow-php/flow
          download-url: https://github.com/flow-php/flow/releases/download/${{ env.RELEASE_TAG }}/flow.phar
          commit-message: |
            Update Homebrew TAP formula: {{formulaName}} to version: {{version}}

            <h2>Change Log</h2>
            <div id="change-log">
              <h4>Changed</h4>
              <ul id="changed">
                <li>Update Homebrew TAP formula: {{formulaName}} to version: {{version}}</li>
              </ul>
            </div>
            <hr/>

            <h2>Description</h2>

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.ACCESS_TOKEN }}
