name: Dependabot - Auto Merge

on:
  workflow_run:
    types: [ completed ]
    workflows: [ "Test Suite" ]

jobs:
  merge-me:
    name: "Merge me!"
    runs-on: ubuntu-latest
    steps:
      - # It is often a desired behavior to merge only when a workflow execution
        # succeeds. This can be changed as needed.
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        name: Merge me!
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}