name: Static Analyze

on:
  pull_request:
  push:
    branches: [ 1.x ]
  schedule: [ { cron: '0 8 * * *' } ]

jobs:
  static-analyze:
    name: Static Analyze
    strategy:
      matrix:
        dependencies: [ locked ]
        php-version: [ 7.4 ]
        operating-system: [ ubuntu-latest ]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          tools: composer:v2
          php-version: ${{ matrix.php-version }}
          ini-values: memory_limit=-1
        env:
          COMPOSER_TOKEN: ${{ secrets.PRIVATE_REPOSITORY_ACCESS }}

      - name: Cache Phive dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.phive
          key: ${{ runner.os }}-phive-${{ hashFiles('**/phars.xml') }}
          restore-keys: |
            ${{ runner.os }}-phive-

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo ::set-output name=dir::$(composer config cache-files-dir)

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
          key: php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-

      - name: Install lowest dependencies
        if: ${{ matrix.dependencies == 'lowest' }}
        run: composer update --prefer-lowest --no-interaction --no-progress --no-suggest

      - name: Install highest dependencies
        if: ${{ matrix.dependencies == 'highest' }}
        run: composer update --no-interaction --no-progress --no-suggest

      - name: Install locked dependencies
        if: ${{ matrix.dependencies == 'locked' }}
        run: composer install --no-interaction --no-progress --no-suggest

      - name: Install tools
        run: composer install --no-interaction --no-progress --no-suggest
        working-directory: ./tools

      - name: Static Analyze
        run: composer static:analyze
